# EvolAgent Configuration File
# This file contains all configurable parameters for the system

# Pipeline Configuration
pipeline:
  max_dev_test_iterations: 80  # Maximum iterations for dev-test loop
  max_parallel_tasks: 1        # Maximum parallel task execution (reduced to prevent resource contention)
  emergency_break_iterations: 85  # Emergency break point (max_dev_test_iterations + 5)

# Memory and RAG Configuration
memory:
  max_tokens_per_chunk: 8192   # Maximum tokens allowed per text chunk
  search_method: "hybrid"     # Search method for semantic search
  semantic_search_limit: 3     # Number of semantic search results to return
  episodic_search_limit: 3     # Number of episodic search results to return
  score_threshold: 0.15        # Minimum confidence score for search results
  hybrid_search_multiplier: 2  # Multiplier for hybrid search prefetch limit

# Model Configuration
models:
  default_embedding_model: "text-embedding-3-small"
  embedding_dimension: 1536
  default_sparse_model: "prithivida/Splade_PP_en_v1"
  
  # Model lists for multi-path sampling
  default_models:
    # - "gemini2.5propreview"
    # - "claude-3-7-sonnet-v1"
    # - "o4-mini"
    - "anthropic.claude-sonnet-4-20250514-v1:0"
    - "anthropic.claude-sonnet-4-20250514-v1:0"
    - "anthropic.claude-sonnet-4-20250514-v1:0"
  temperature: 0.5
  max_tokens: 32000

# Node Configuration
nodes:
  plan_history_length: 12  # Default history length for plan node
  dev_history_length: 8        # History length for dev node
  test_history_length: 8       # History length for test node
  critic_length: 6
  max_history_tokens: 184320  # 180k tokens
  max_compress_rounds: 3 # Maximum number of compression loops

# History Compression Configuration
compression:
  # Compression behavior
  max_attempts: 3              # Maximum compression attempts per cycle
  min_savings: 50              # Minimum token savings to apply compression
  min_length: 200              # Minimum content length to consider for compression
  min_output_tokens: 50        # Minimum tokens in compressed output
  max_output_tokens: 2048      # Maximum tokens in compressed output
  target_ratio: 3              # Target compression ratio (original/compressed)
  reference_max_length: 1000   # Maximum reference content length for context
  
  # LLM settings for compression
  model: "gpt-4.1"         # Model to use for compression
  temperature: 0.1             # Temperature for compression (lower = more consistent)
  timeout: 60                  # Timeout for compression API calls
  
  # Fallback removal settings
  removal_target_ratio: 0.8    # Target ratio of max_tokens after removal (80%)
  removal_max_items: 10        # Maximum items to remove in one cycle
  
  # Code compression settings
  code_compression_enabled: true     # Enable specialized code compression
  code_target_reduction: 0.5         # Target reduction ratio for code (50%)
  output_max_length: 500              # Maximum length for compressed code output

# Environment Configuration
environment:
  workspace_dir: "workspace"   # Directory for downloaded files
  qdrant_persist_path: "./qdrant"  # Path for Qdrant database
  
# Logging Configuration
logging:
  level: "INFO"                # Log level (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/evolagent.log"
  folder_path: "logs"
  max_file_size: 104857600     # 100MB
  backup_count: 5              # Number of backup log files
  console_output: true         # Whether to output logs to console

# Task Configuration
task:
  summarize_max_tokens: 600   # Max tokens for task summarization
  summarize_temperature: 0.2   # Temperature for task summarization
  max_title_words: 15          # Maximum words in task title

# Timeout and Retry Configuration
timeout:
  api_timeout: 800              # API request timeout in seconds
  max_retries: 3               # Maximum API retry attempts
  retry_delay: 1.0             # Base retry delay in seconds
  exponential_backoff: true    # Whether to use exponential backoff 