# EvolAgent Configuration File
# This file contains all configurable parameters for the system

# Pipeline Configuration
pipeline:
  max_dev_test_iterations: 50  # Maximum iterations for dev-test loop
  max_parallel_tasks: 3        # Maximum parallel task execution
  emergency_break_iterations: 55  # Emergency break point (max_dev_test_iterations + 5)

# Memory and RAG Configuration
memory:
  max_tokens_per_chunk: 8192   # Maximum tokens allowed per text chunk
  semantic_search_limit: 4     # Number of semantic search results to return
  episodic_search_limit: 4     # Number of episodic search results to return
  score_threshold: 0.1        # Minimum confidence score for search results
  hybrid_search_multiplier: 2  # Multiplier for hybrid search prefetch limit

# Model Configuration
models:
  default_embedding_model: "text-embedding-3-small"
  embedding_dimension: 1536
  default_sparse_model: "prithivida/Splade_PP_en_v1"
  
  # Model lists for multi-path sampling
  default_models:
    - "o4-mini"
    - "anthropic.claude-sonnet-4-20250514-v1:0"
    - "anthropic.claude-opus-4-20250514-v1:0"

  max_tokens: 32000

# Node Configuration
nodes:
  max_history_tokens: 199999   # Maximum tokens in history before maintenance
  adaptive_history_length: 10  # Default history length for plan node
  dev_history_length: 4        # History length for dev node
  test_history_length: 6       # History length for test node

# Environment Configuration
environment:
  workspace_dir: "workspace"   # Directory for downloaded files
  qdrant_persist_path: "./qdrant_data"  # Path for Qdrant database
  
# Logging Configuration
logging:
  level: "INFO"                # Log level (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/evolagent.log"
  max_file_size: 10485760      # 10MB
  backup_count: 5              # Number of backup log files
  console_output: true         # Whether to output logs to console

# Task Configuration
task:
  summarize_max_tokens: 1000   # Max tokens for task summarization
  summarize_temperature: 0.1   # Temperature for task summarization
  max_title_words: 15          # Maximum words in task title

# Timeout and Retry Configuration
timeout:
  api_timeout: 30              # API request timeout in seconds
  max_retries: 3               # Maximum API retry attempts
  retry_delay: 1.0             # Base retry delay in seconds
  exponential_backoff: true    # Whether to use exponential backoff 